name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  macos-run-tests:
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run tests
        run: swift test

  linux-run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run tests
        run: swift test
